import Insider from "@/components/pages/Insider";
import Outsider from "@/components/pages/Outsider";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useUserStore } from "src/global/user";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const {role} = useUserStore((state) => state.user);
  console.log({role})
  return (
    <div className={styles.container}>
      <Head>
        <title>Flat Management System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
         <Insider role={role}/>
        
    </div>
  );
};

export default Home;
